name: CodeDoc

on:
  push:
    branches: [main]

jobs:
  notify_codedoc:
    runs-on: ubuntu-latest
    steps:
      - name: PING codedoc repository
        run: |
          curl -X POST  \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.GH_DISPATCH_TOKEN }}' \
          https://api.github.com/repos/frenchyeti/interruptor-codedoc/dispatches \
          --data '{"event_type": "build-doc", "client_payload": {}}'